// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNF_F5bqsp6mChtEGvqhIyUbpvyKddTzE',
    appId: '1:663328254220:web:db07244e1ce023dcfdc129',
    messagingSenderId: '663328254220',
    projectId: 'banoqabil-d766e',
    authDomain: 'banoqabil-d766e.firebaseapp.com',
    storageBucket: 'banoqabil-d766e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByvx6FaxTBaMbFKmjvEttnakFNfKjqk6Q',
    appId: '1:663328254220:android:14474da90eb80f54fdc129',
    messagingSenderId: '663328254220',
    projectId: 'banoqabil-d766e',
    storageBucket: 'banoqabil-d766e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD2JBvdpvfZyc-qDRwlbMX0dbJXfO97w8',
    appId: '1:663328254220:ios:0aea7b72efad98f5fdc129',
    messagingSenderId: '663328254220',
    projectId: 'banoqabil-d766e',
    storageBucket: 'banoqabil-d766e.appspot.com',
    iosClientId: '663328254220-3mh5n3gvboblhgc6ghqdbth196jd4j0t.apps.googleusercontent.com',
    iosBundleId: 'banoqabil',
  );
}
